import { Candidate } from '../../models/content.model';

/**
 * Fiches des candidats — version française.
 *
 * À COMPLÉTER : profils fictifs, à remplacer par les informations réelles.
 * Ajouter `photo` (ex. `/img/candidats/<slug>.jpg`) pour chaque candidat.
 */
export const candidatesFr: Candidate[] = [
  {
    slug: 'jean-robert-pierre-louis',
    name: 'Jean-Robert Pierre-Louis',
    subtitle: 'Candidat à la présidence',
    // photo: '/img/candidats/jean-robert-pierre-louis.jpg',
    position: 'Président de la République',
    constituency: 'Circonscription nationale',
    party: 'DEBOUT PATRIOTES',
    professions: ['Économiste'],
    birthplace: 'Port-au-Prince',
    quote: 'Se tenir debout, c\'est refuser que la résignation décide à notre place.',
    bio: [
      'Né à Port-au-Prince, Jean-Robert Pierre-Louis a grandi au contact des réalités de sa communauté, où il s’est très tôt engagé dans la vie associative.',
      'Économiste de métier, Jean-Robert met depuis plus de quinze ans ses compétences au service de la population, sur le terrain comme dans les institutions.',
      'Membre de DEBOUT PATRIOTES dès sa constitution, il porte aujourd’hui les couleurs du groupement pour la présidence de la République.',
    ],
    priorities: [
      { title: 'Sécurité des familles', desc: 'Rétablir la présence de l\'État et protéger les quartiers comme les sections communales.', icon: 'pi-shield' },
      { title: 'Santé de proximité', desc: 'Rouvrir et équiper les centres de santé communautaires.', icon: 'pi-heart' },
      { title: 'Transparence', desc: 'Rendre compte publiquement de chaque gourde dépensée.', icon: 'pi-eye' },
    ],
    career: [
      { period: '2026', title: 'Investi candidat de DEBOUT PATRIOTES', desc: 'Candidat à la présidence' },
      { period: '2018 — 2026', title: 'Économiste — responsable de projets', desc: 'Coordination de programmes au bénéfice des communautés locales.' },
      { period: '2010 — 2018', title: 'Engagement associatif', desc: 'Animation d’organisations citoyennes à Port-au-Prince.' },
    ],
    education: ['Licence — Université d’État d’Haïti', 'Certificat en gouvernance locale'],
    contact: { email: 'jean-robert-pierre-louis@deboutpatriotes.ht' },
  },
  {
    slug: 'marie-claude-joseph',
    name: 'Marie-Claude Joseph',
    subtitle: 'Candidate au Sénat · Ouest',
    // photo: '/img/candidats/marie-claude-joseph.jpg',
    position: 'Sénatrice',
    constituency: 'Département de l\'Ouest',
    party: 'DEBOUT PATRIOTES',
    professions: ['Avocate'],
    birthplace: 'Pétion-Ville',
    quote: 'Servir Haïti, c\'est d\'abord écouter celles et ceux qui la font vivre chaque jour.',
    bio: [
      'Née à Pétion-Ville, Marie-Claude Joseph a grandi au contact des réalités de sa communauté, où elle s’est très tôt engagée dans la vie associative.',
      'Avocate de métier, Marie-Claude met depuis plus de quinze ans ses compétences au service de la population, sur le terrain comme dans les institutions.',
      'Membre de DEBOUT PATRIOTES dès sa constitution, elle porte aujourd’hui les couleurs du groupement pour le poste de sénatrice (Département de l\'Ouest).',
    ],
    priorities: [
      { title: 'Emploi des jeunes', desc: 'Soutenir la formation professionnelle et l\'entrepreneuriat local.', icon: 'pi-briefcase' },
      { title: 'École pour tous', desc: 'Garantir l\'accès à une éducation de qualité dans chaque commune.', icon: 'pi-book' },
      { title: 'Diaspora', desc: 'Associer la diaspora à la reconstruction du pays.', icon: 'pi-globe' },
    ],
    career: [
      { period: '2026', title: 'Investie candidate de DEBOUT PATRIOTES', desc: 'Candidate au Sénat · Ouest' },
      { period: '2018 — 2026', title: 'Avocate — responsable de projets', desc: 'Coordination de programmes au bénéfice des communautés locales.' },
      { period: '2010 — 2018', title: 'Engagement associatif', desc: 'Animation d’organisations citoyennes à Pétion-Ville.' },
    ],
    education: ['Licence — Université d’État d’Haïti', 'Certificat en gouvernance locale'],
    contact: { email: 'marie-claude-joseph@deboutpatriotes.ht' },
  },
  {
    slug: 'wilner-saint-fleur',
    name: 'Wilner Saint-Fleur',
    subtitle: 'Candidat au Sénat · Artibonite',
    // photo: '/img/candidats/wilner-saint-fleur.jpg',
    position: 'Sénateur',
    constituency: 'Département de l\'Artibonite',
    party: 'DEBOUT PATRIOTES',
    professions: ['Agronome'],
    birthplace: 'Saint-Marc',
    quote: 'Se tenir debout, c\'est refuser que la résignation décide à notre place.',
    bio: [
      'Né à Saint-Marc, Wilner Saint-Fleur a grandi au contact des réalités de sa communauté, où il s’est très tôt engagé dans la vie associative.',
      'Agronome de métier, Wilner met depuis plus de quinze ans ses compétences au service de la population, sur le terrain comme dans les institutions.',
      'Membre de DEBOUT PATRIOTES dès sa constitution, il porte aujourd’hui les couleurs du groupement pour le poste de sénateur (Département de l\'Artibonite).',
    ],
    priorities: [
      { title: 'Production nationale', desc: 'Relancer l\'agriculture et la transformation locale des produits.', icon: 'pi-sun' },
      { title: 'Infrastructures', desc: 'Routes, eau potable et électricité pour désenclaver le territoire.', icon: 'pi-building' },
      { title: 'Sécurité des familles', desc: 'Rétablir la présence de l\'État et protéger les quartiers comme les sections communales.', icon: 'pi-shield' },
    ],
    career: [
      { period: '2026', title: 'Investi candidat de DEBOUT PATRIOTES', desc: 'Candidat au Sénat · Artibonite' },
      { period: '2018 — 2026', title: 'Agronome — responsable de projets', desc: 'Coordination de programmes au bénéfice des communautés locales.' },
      { period: '2010 — 2018', title: 'Engagement associatif', desc: 'Animation d’organisations citoyennes à Saint-Marc.' },
    ],
    education: ['Licence — Université d’État d’Haïti', 'Certificat en gouvernance locale'],
    contact: { email: 'wilner-saint-fleur@deboutpatriotes.ht' },
  },
  {
    slug: 'nadege-celestin',
    name: 'Nadège Célestin',
    subtitle: 'Candidate à la députation · Port-au-Prince',
    // photo: '/img/candidats/nadege-celestin.jpg',
    position: 'Députée',
    constituency: 'Circonscription de Port-au-Prince',
    party: 'DEBOUT PATRIOTES',
    professions: ['Médecin'],
    birthplace: 'Port-au-Prince',
    quote: 'Servir Haïti, c\'est d\'abord écouter celles et ceux qui la font vivre chaque jour.',
    bio: [
      'Née à Port-au-Prince, Nadège Célestin a grandi au contact des réalités de sa communauté, où elle s’est très tôt engagée dans la vie associative.',
      'Médecin de métier, Nadège met depuis plus de quinze ans ses compétences au service de la population, sur le terrain comme dans les institutions.',
      'Membre de DEBOUT PATRIOTES dès sa constitution, elle porte aujourd’hui les couleurs du groupement pour le poste de députée (Circonscription de Port-au-Prince).',
    ],
    priorities: [
      { title: 'Santé de proximité', desc: 'Rouvrir et équiper les centres de santé communautaires.', icon: 'pi-heart' },
      { title: 'Transparence', desc: 'Rendre compte publiquement de chaque gourde dépensée.', icon: 'pi-eye' },
      { title: 'Emploi des jeunes', desc: 'Soutenir la formation professionnelle et l\'entrepreneuriat local.', icon: 'pi-briefcase' },
    ],
    career: [
      { period: '2026', title: 'Investie candidate de DEBOUT PATRIOTES', desc: 'Candidate à la députation · Port-au-Prince' },
      { period: '2018 — 2026', title: 'Médecin — responsable de projets', desc: 'Coordination de programmes au bénéfice des communautés locales.' },
      { period: '2010 — 2018', title: 'Engagement associatif', desc: 'Animation d’organisations citoyennes à Port-au-Prince.' },
    ],
    education: ['Licence — Université d’État d’Haïti', 'Certificat en gouvernance locale'],
    contact: { email: 'nadege-celestin@deboutpatriotes.ht' },
  },
  {
    slug: 'frantz-desir',
    name: 'Frantz Désir',
    subtitle: 'Candidat au Sénat · Nord',
    // photo: '/img/candidats/frantz-desir.jpg',
    position: 'Sénateur',
    constituency: 'Département du Nord',
    party: 'DEBOUT PATRIOTES',
    professions: ['Ingénieur civil'],
    birthplace: 'Limbé',
    quote: 'Se tenir debout, c\'est refuser que la résignation décide à notre place.',
    bio: [
      'Né à Limbé, Frantz Désir a grandi au contact des réalités de sa communauté, où il s’est très tôt engagé dans la vie associative.',
      'Ingénieur civil de métier, Frantz met depuis plus de quinze ans ses compétences au service de la population, sur le terrain comme dans les institutions.',
      'Membre de DEBOUT PATRIOTES dès sa constitution, il porte aujourd’hui les couleurs du groupement pour le poste de sénateur (Département du Nord).',
    ],
    priorities: [
      { title: 'École pour tous', desc: 'Garantir l\'accès à une éducation de qualité dans chaque commune.', icon: 'pi-book' },
      { title: 'Diaspora', desc: 'Associer la diaspora à la reconstruction du pays.', icon: 'pi-globe' },
      { title: 'Production nationale', desc: 'Relancer l\'agriculture et la transformation locale des produits.', icon: 'pi-sun' },
    ],
    career: [
      { period: '2026', title: 'Investi candidat de DEBOUT PATRIOTES', desc: 'Candidat au Sénat · Nord' },
      { period: '2018 — 2026', title: 'Ingénieur civil — responsable de projets', desc: 'Coordination de programmes au bénéfice des communautés locales.' },
      { period: '2010 — 2018', title: 'Engagement associatif', desc: 'Animation d’organisations citoyennes à Limbé.' },
    ],
    education: ['Licence — Université d’État d’Haïti', 'Certificat en gouvernance locale'],
    contact: { email: 'frantz-desir@deboutpatriotes.ht' },
  },
  {
    slug: 'guerline-augustin',
    name: 'Guerline Augustin',
    subtitle: 'Candidate à la députation · Jacmel',
    // photo: '/img/candidats/guerline-augustin.jpg',
    position: 'Députée',
    constituency: 'Circonscription de Jacmel',
    party: 'DEBOUT PATRIOTES',
    professions: ['Enseignante'],
    birthplace: 'Jacmel',
    quote: 'Servir Haïti, c\'est d\'abord écouter celles et ceux qui la font vivre chaque jour.',
    bio: [
      'Née à Jacmel, Guerline Augustin a grandi au contact des réalités de sa communauté, où elle s’est très tôt engagée dans la vie associative.',
      'Enseignante de métier, Guerline met depuis plus de quinze ans ses compétences au service de la population, sur le terrain comme dans les institutions.',
      'Membre de DEBOUT PATRIOTES dès sa constitution, elle porte aujourd’hui les couleurs du groupement pour le poste de députée (Circonscription de Jacmel).',
    ],
    priorities: [
      { title: 'Infrastructures', desc: 'Routes, eau potable et électricité pour désenclaver le territoire.', icon: 'pi-building' },
      { title: 'Sécurité des familles', desc: 'Rétablir la présence de l\'État et protéger les quartiers comme les sections communales.', icon: 'pi-shield' },
      { title: 'Santé de proximité', desc: 'Rouvrir et équiper les centres de santé communautaires.', icon: 'pi-heart' },
    ],
    career: [
      { period: '2026', title: 'Investie candidate de DEBOUT PATRIOTES', desc: 'Candidate à la députation · Jacmel' },
      { period: '2018 — 2026', title: 'Enseignante — responsable de projets', desc: 'Coordination de programmes au bénéfice des communautés locales.' },
      { period: '2010 — 2018', title: 'Engagement associatif', desc: 'Animation d’organisations citoyennes à Jacmel.' },
    ],
    education: ['Licence — Université d’État d’Haïti', 'Certificat en gouvernance locale'],
    contact: { email: 'guerline-augustin@deboutpatriotes.ht' },
  },
  {
    slug: 'ricardo-beauvais',
    name: 'Ricardo Beauvais',
    subtitle: 'Candidat à la députation · Les Cayes',
    // photo: '/img/candidats/ricardo-beauvais.jpg',
    position: 'Député',
    constituency: 'Circonscription des Cayes',
    party: 'DEBOUT PATRIOTES',
    professions: ['Entrepreneur'],
    birthplace: 'Les Cayes',
    quote: 'Se tenir debout, c\'est refuser que la résignation décide à notre place.',
    bio: [
      'Né à Les Cayes, Ricardo Beauvais a grandi au contact des réalités de sa communauté, où il s’est très tôt engagé dans la vie associative.',
      'Entrepreneur de métier, Ricardo met depuis plus de quinze ans ses compétences au service de la population, sur le terrain comme dans les institutions.',
      'Membre de DEBOUT PATRIOTES dès sa constitution, il porte aujourd’hui les couleurs du groupement pour le poste de député (Circonscription des Cayes).',
    ],
    priorities: [
      { title: 'Transparence', desc: 'Rendre compte publiquement de chaque gourde dépensée.', icon: 'pi-eye' },
      { title: 'Emploi des jeunes', desc: 'Soutenir la formation professionnelle et l\'entrepreneuriat local.', icon: 'pi-briefcase' },
      { title: 'École pour tous', desc: 'Garantir l\'accès à une éducation de qualité dans chaque commune.', icon: 'pi-book' },
    ],
    career: [
      { period: '2026', title: 'Investi candidat de DEBOUT PATRIOTES', desc: 'Candidat à la députation · Les Cayes' },
      { period: '2018 — 2026', title: 'Entrepreneur — responsable de projets', desc: 'Coordination de programmes au bénéfice des communautés locales.' },
      { period: '2010 — 2018', title: 'Engagement associatif', desc: 'Animation d’organisations citoyennes à Les Cayes.' },
    ],
    education: ['Licence — Université d’État d’Haïti', 'Certificat en gouvernance locale'],
    contact: { email: 'ricardo-beauvais@deboutpatriotes.ht' },
  },
  {
    slug: 'stephanie-lamour',
    name: 'Stéphanie Lamour',
    subtitle: 'Candidate au Sénat · Sud-Est',
    // photo: '/img/candidats/stephanie-lamour.jpg',
    position: 'Sénatrice',
    constituency: 'Département du Sud-Est',
    party: 'DEBOUT PATRIOTES',
    professions: ['Journaliste'],
    birthplace: 'Bainet',
    quote: 'Servir Haïti, c\'est d\'abord écouter celles et ceux qui la font vivre chaque jour.',
    bio: [
      'Née à Bainet, Stéphanie Lamour a grandi au contact des réalités de sa communauté, où elle s’est très tôt engagée dans la vie associative.',
      'Journaliste de métier, Stéphanie met depuis plus de quinze ans ses compétences au service de la population, sur le terrain comme dans les institutions.',
      'Membre de DEBOUT PATRIOTES dès sa constitution, elle porte aujourd’hui les couleurs du groupement pour le poste de sénatrice (Département du Sud-Est).',
    ],
    priorities: [
      { title: 'Diaspora', desc: 'Associer la diaspora à la reconstruction du pays.', icon: 'pi-globe' },
      { title: 'Production nationale', desc: 'Relancer l\'agriculture et la transformation locale des produits.', icon: 'pi-sun' },
      { title: 'Infrastructures', desc: 'Routes, eau potable et électricité pour désenclaver le territoire.', icon: 'pi-building' },
    ],
    career: [
      { period: '2026', title: 'Investie candidate de DEBOUT PATRIOTES', desc: 'Candidate au Sénat · Sud-Est' },
      { period: '2018 — 2026', title: 'Journaliste — responsable de projets', desc: 'Coordination de programmes au bénéfice des communautés locales.' },
      { period: '2010 — 2018', title: 'Engagement associatif', desc: 'Animation d’organisations citoyennes à Bainet.' },
    ],
    education: ['Licence — Université d’État d’Haïti', 'Certificat en gouvernance locale'],
    contact: { email: 'stephanie-lamour@deboutpatriotes.ht' },
  },
  {
    slug: 'emmanuel-jean-baptiste',
    name: 'Emmanuel Jean-Baptiste',
    subtitle: 'Candidat à la députation · Cap-Haïtien',
    // photo: '/img/candidats/emmanuel-jean-baptiste.jpg',
    position: 'Député',
    constituency: 'Circonscription du Cap-Haïtien',
    party: 'DEBOUT PATRIOTES',
    professions: ['Gestionnaire portuaire'],
    birthplace: 'Cap-Haïtien',
    quote: 'Se tenir debout, c\'est refuser que la résignation décide à notre place.',
    bio: [
      'Né à Cap-Haïtien, Emmanuel Jean-Baptiste a grandi au contact des réalités de sa communauté, où il s’est très tôt engagé dans la vie associative.',
      'Gestionnaire portuaire de métier, Emmanuel met depuis plus de quinze ans ses compétences au service de la population, sur le terrain comme dans les institutions.',
      'Membre de DEBOUT PATRIOTES dès sa constitution, il porte aujourd’hui les couleurs du groupement pour le poste de député (Circonscription du Cap-Haïtien).',
    ],
    priorities: [
      { title: 'Sécurité des familles', desc: 'Rétablir la présence de l\'État et protéger les quartiers comme les sections communales.', icon: 'pi-shield' },
      { title: 'Santé de proximité', desc: 'Rouvrir et équiper les centres de santé communautaires.', icon: 'pi-heart' },
      { title: 'Transparence', desc: 'Rendre compte publiquement de chaque gourde dépensée.', icon: 'pi-eye' },
    ],
    career: [
      { period: '2026', title: 'Investi candidat de DEBOUT PATRIOTES', desc: 'Candidat à la députation · Cap-Haïtien' },
      { period: '2018 — 2026', title: 'Gestionnaire portuaire — responsable de projets', desc: 'Coordination de programmes au bénéfice des communautés locales.' },
      { period: '2010 — 2018', title: 'Engagement associatif', desc: 'Animation d’organisations citoyennes à Cap-Haïtien.' },
    ],
    education: ['Licence — Université d’État d’Haïti', 'Certificat en gouvernance locale'],
    contact: { email: 'emmanuel-jean-baptiste@deboutpatriotes.ht' },
  },
  {
    slug: 'rose-andree-michel',
    name: 'Rose-Andrée Michel',
    subtitle: 'Candidate au Sénat · Grand\'Anse',
    // photo: '/img/candidats/rose-andree-michel.jpg',
    position: 'Sénatrice',
    constituency: 'Département de la Grand\'Anse',
    party: 'DEBOUT PATRIOTES',
    professions: ['Infirmière'],
    birthplace: 'Jérémie',
    quote: 'Servir Haïti, c\'est d\'abord écouter celles et ceux qui la font vivre chaque jour.',
    bio: [
      'Née à Jérémie, Rose-Andrée Michel a grandi au contact des réalités de sa communauté, où elle s’est très tôt engagée dans la vie associative.',
      'Infirmière de métier, Rose-Andrée met depuis plus de quinze ans ses compétences au service de la population, sur le terrain comme dans les institutions.',
      'Membre de DEBOUT PATRIOTES dès sa constitution, elle porte aujourd’hui les couleurs du groupement pour le poste de sénatrice (Département de la Grand\'Anse).',
    ],
    priorities: [
      { title: 'Emploi des jeunes', desc: 'Soutenir la formation professionnelle et l\'entrepreneuriat local.', icon: 'pi-briefcase' },
      { title: 'École pour tous', desc: 'Garantir l\'accès à une éducation de qualité dans chaque commune.', icon: 'pi-book' },
      { title: 'Diaspora', desc: 'Associer la diaspora à la reconstruction du pays.', icon: 'pi-globe' },
    ],
    career: [
      { period: '2026', title: 'Investie candidate de DEBOUT PATRIOTES', desc: 'Candidate au Sénat · Grand\'Anse' },
      { period: '2018 — 2026', title: 'Infirmière — responsable de projets', desc: 'Coordination de programmes au bénéfice des communautés locales.' },
      { period: '2010 — 2018', title: 'Engagement associatif', desc: 'Animation d’organisations citoyennes à Jérémie.' },
    ],
    education: ['Licence — Université d’État d’Haïti', 'Certificat en gouvernance locale'],
    contact: { email: 'rose-andree-michel@deboutpatriotes.ht' },
  },
  {
    slug: 'patrick-dorvil',
    name: 'Patrick Dorvil',
    subtitle: 'Candidat à la députation · Hinche',
    // photo: '/img/candidats/patrick-dorvil.jpg',
    position: 'Député',
    constituency: 'Circonscription de Hinche',
    party: 'DEBOUT PATRIOTES',
    professions: ['Animateur communautaire'],
    birthplace: 'Hinche',
    quote: 'Se tenir debout, c\'est refuser que la résignation décide à notre place.',
    bio: [
      'Né à Hinche, Patrick Dorvil a grandi au contact des réalités de sa communauté, où il s’est très tôt engagé dans la vie associative.',
      'Animateur communautaire de métier, Patrick met depuis plus de quinze ans ses compétences au service de la population, sur le terrain comme dans les institutions.',
      'Membre de DEBOUT PATRIOTES dès sa constitution, il porte aujourd’hui les couleurs du groupement pour le poste de député (Circonscription de Hinche).',
    ],
    priorities: [
      { title: 'Production nationale', desc: 'Relancer l\'agriculture et la transformation locale des produits.', icon: 'pi-sun' },
      { title: 'Infrastructures', desc: 'Routes, eau potable et électricité pour désenclaver le territoire.', icon: 'pi-building' },
      { title: 'Sécurité des familles', desc: 'Rétablir la présence de l\'État et protéger les quartiers comme les sections communales.', icon: 'pi-shield' },
    ],
    career: [
      { period: '2026', title: 'Investi candidat de DEBOUT PATRIOTES', desc: 'Candidat à la députation · Hinche' },
      { period: '2018 — 2026', title: 'Animateur communautaire — responsable de projets', desc: 'Coordination de programmes au bénéfice des communautés locales.' },
      { period: '2010 — 2018', title: 'Engagement associatif', desc: 'Animation d’organisations citoyennes à Hinche.' },
    ],
    education: ['Licence — Université d’État d’Haïti', 'Certificat en gouvernance locale'],
    contact: { email: 'patrick-dorvil@deboutpatriotes.ht' },
  },
  {
    slug: 'fabienne-toussaint',
    name: 'Fabienne Toussaint',
    subtitle: 'Candidate au Sénat · Nord-Est',
    // photo: '/img/candidats/fabienne-toussaint.jpg',
    position: 'Sénatrice',
    constituency: 'Département du Nord-Est',
    party: 'DEBOUT PATRIOTES',
    professions: ['Juriste'],
    birthplace: 'Fort-Liberté',
    quote: 'Servir Haïti, c\'est d\'abord écouter celles et ceux qui la font vivre chaque jour.',
    bio: [
      'Née à Fort-Liberté, Fabienne Toussaint a grandi au contact des réalités de sa communauté, où elle s’est très tôt engagée dans la vie associative.',
      'Juriste de métier, Fabienne met depuis plus de quinze ans ses compétences au service de la population, sur le terrain comme dans les institutions.',
      'Membre de DEBOUT PATRIOTES dès sa constitution, elle porte aujourd’hui les couleurs du groupement pour le poste de sénatrice (Département du Nord-Est).',
    ],
    priorities: [
      { title: 'Santé de proximité', desc: 'Rouvrir et équiper les centres de santé communautaires.', icon: 'pi-heart' },
      { title: 'Transparence', desc: 'Rendre compte publiquement de chaque gourde dépensée.', icon: 'pi-eye' },
      { title: 'Emploi des jeunes', desc: 'Soutenir la formation professionnelle et l\'entrepreneuriat local.', icon: 'pi-briefcase' },
    ],
    career: [
      { period: '2026', title: 'Investie candidate de DEBOUT PATRIOTES', desc: 'Candidate au Sénat · Nord-Est' },
      { period: '2018 — 2026', title: 'Juriste — responsable de projets', desc: 'Coordination de programmes au bénéfice des communautés locales.' },
      { period: '2010 — 2018', title: 'Engagement associatif', desc: 'Animation d’organisations citoyennes à Fort-Liberté.' },
    ],
    education: ['Licence — Université d’État d’Haïti', 'Certificat en gouvernance locale'],
    contact: { email: 'fabienne-toussaint@deboutpatriotes.ht' },
  },
];
